server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/quickbite_order?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
