server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurants/**
          filters:
            - AuthenticationFilter
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/api/menus/**
          filters:
            - AuthenticationFilter
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
          filters:
            - AuthenticationFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
          filters:
            - AuthenticationFilter
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/delivery/**
          filters:
            - AuthenticationFilter
        - id: order-reviews
          uri: lb://order-service
          predicates:
            - Path=/api/reviews/**
          filters:
            - AuthenticationFilter
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - AuthenticationFilter

        - id: openapi-auth
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth, /v3/api-docs
        - id: openapi-restaurant
          uri: lb://restaurant-service
          predicates:
            - Path=/v3/api-docs/restaurant
          filters:
            - RewritePath=/v3/api-docs/restaurant, /v3/api-docs
        - id: openapi-menu
          uri: lb://menu-service
          predicates:
            - Path=/v3/api-docs/menu
          filters:
            - RewritePath=/v3/api-docs/menu, /v3/api-docs
        - id: openapi-cart
          uri: lb://cart-service
          predicates:
            - Path=/v3/api-docs/cart
          filters:
            - RewritePath=/v3/api-docs/cart, /v3/api-docs
        - id: openapi-order
          uri: lb://order-service
          predicates:
            - Path=/v3/api-docs/order
          filters:
            - RewritePath=/v3/api-docs/order, /v3/api-docs
        - id: openapi-payment
          uri: lb://payment-service
          predicates:
            - Path=/v3/api-docs/payment
          filters:
            - RewritePath=/v3/api-docs/payment, /v3/api-docs
        - id: openapi-delivery
          uri: lb://delivery-service
          predicates:
            - Path=/v3/api-docs/delivery
          filters:
            - RewritePath=/v3/api-docs/delivery, /v3/api-docs
        - id: openapi-review
          uri: lb://review-service
          predicates:
            - Path=/v3/api-docs/review
          filters:
            - RewritePath=/v3/api-docs/review, /v3/api-docs
        - id: openapi-notification
          uri: lb://notification-service
          predicates:
            - Path=/v3/api-docs/notification
          filters:
            - RewritePath=/v3/api-docs/notification, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: auth-service
        url: /v3/api-docs/auth
      - name: restaurant-service
        url: /v3/api-docs/restaurant
      - name: menu-service
        url: /v3/api-docs/menu
      - name: cart-service
        url: /v3/api-docs/cart
      - name: order-service
        url: /v3/api-docs/order
      - name: payment-service
        url: /v3/api-docs/payment
      - name: delivery-service
        url: /v3/api-docs/delivery
      - name: review-service
        url: /v3/api-docs/review
      - name: notification-service
        url: /v3/api-docs/notification

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

